import pygame

TITLE = "Zombie Game"
WIDTH = 1200
HEIGHT = 900
SCREEN_COLOR = (112, 72, 60)
TEXT_COLOR = (255, 255, 255)
FRAMES_PER_SECOND = 90

MOVEMENT = 3
MOVEMENT_LEFT = "left"
MOVEMENT_RIGHT = "right"
MOVEMENT_UP = "up"
MOVEMENT_DOWN = "down"
AXIS_X = "x"
AXIS_Y = "y"
MAX_ZOMBIES = 64
HEALTH = 16
MIN_HEALTH = 0
MAX_HEALTH = 16
ZOMBIE_TICKS_PER_ACT = 4
ZOMBIE_LEVEL_UP_TICK_COUNT = FRAMES_PER_SECOND * 4
ZOMBIE_LEVEL_START = 0
ZOMBIE_DETECTION_DISTANCE = 300
ZOMBIE_LEVEL_UP_CHANCE = 0.05
ZOMBIE_CHANGE_DIRECTION_TICK_COUNT = 32
ZOMBIE_TICKS_TO_SPAWN = 4

PLAYER_TICKS_PER_ACT = 2

MOVEMENT_TOUCH_INDEX = 4
